### ISSUE TITLE
Setup Basic UI

### ISSUE THREAD

**Issue by namirsab** [namirsab/courses-app#1]
## Description
Setup basic UI, with a header, content and bottom navigation.
![image](https://user-images.githubusercontent.com/6980777/115461536-d375be80-a229-11eb-86d6-b6c438da18b3.png)

## Acceptance Criteria
* It should be responsive, working for different screen sizes
* The user should be able to navigate between the Courses page and the Students page
* The header should display the title according to the page that's currently selected.

## Complexity
Small

## Tasks
* [x] Install `react-router-dom`
* [x] Define Routes `/courses` and `/students`
* [x] Make the `/` route redirect to `/courses`
* [x] Create components for:
    * [x] Navigation
    * [x] CoursesPage
    * [x] StudentsPage
* [x] Make the header change its text depending on the location
